const sampleListings = [
  {
    title: "Majestic Heritage Palace",
    description: "Experience royal living in this 200-year-old palace with intricate carvings and lush gardens.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=800" },
    price: 12500,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Serene Backwater Villa",
    description: "Wake up to the gentle sounds of water in the heart of the Alleppey backwaters.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1593181629936-11c609b8db9b?q=80&w=800" },
    price: 8500,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Traditional Rajasthani Haveli",
    description: "Authentic experience in a restored haveli featuring traditional frescoes and courtyards.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?q=80&w=800" },
    price: 4000,
    location: "Jodhpur",
    country: "India",
  },
  {
    title: "Tea Garden Estate Bungalow",
    description: "Stay in a colonial-era bungalow surrounded by rolling hills of tea plantations.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=800" },
    price: 7200,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Riverfront Spiritual Retreat",
    description: "Find peace in this quiet retreat right on the banks of the holy river Ganges.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800" },
    price: 2500,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Boutique Lutyens Home",
    description: "A stylishly renovated bungalow in one of Delhi's most prestigious neighborhoods.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=800" },
    price: 11000,
    location: "New Delhi",
    country: "India",
  },
  {
    title: "Portuguese Pool Villa",
    description: "Classic Goan villa with vibrant colors, private pool, and towering palm trees.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800" },
    price: 13000,
    location: "Anjuna, Goa",
    country: "India",
  },
  {
    title: "Himalayan Monastery View Suite",
    description: "Spectacular views of the Thiksey Monastery and the surrounding Indus valley.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?q=80&w=800" },
    price: 4800,
    location: "Leh",
    country: "India",
  },
  {
    title: "Coffee Estate Cottage",
    description: "Nested in the woods, this cottage is perfect for a quiet weekend in the hills.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501183638710-841dd1904471?q=80&w=800" },
    price: 5200,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Udaipur Lakeside Palace",
    description: "Experience the magic of the Lake City from this luxury palace-themed stay.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800" },
    price: 8800,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Varanasi Ghat Guesthouse",
    description: "Watch the morning rituals and evening aarti from your private balcony on the ghat.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?q=80&w=800" },
    price: 1800,
    location: "Varanasi",
    country: "India",
  },
  {
    title: "Wayanad Treehouse Escape",
    description: "Live high above the forest floor in a luxury treehouse with modern amenities.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?q=80&w=800" },
    price: 9500,
    location: "Wayanad",
    country: "India",
  },
  {
    title: "Silicon Valley Studio",
    description: "A modern, chic studio loft centrally located in the heart of the IT hub.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800" },
    price: 4500,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Mussoorie Valley View Penthouse",
    description: "Enjoy 360-degree views of the Mussoorie hills from your private rooftop terrace.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?q=80&w=800" },
    price: 7500,
    location: "Mussoorie",
    country: "India",
  },
  {
    title: "Dal Lake Luxury Houseboat",
    description: "A floating palace on the serene waters of Dal Lake, featuring hand-carved cedar wood.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1593181629936-11c609b8db9b?q=80&w=800" },
    price: 11000,
    location: "Srinagar",
    country: "India",
  },
  {
    title: "Pine Forest Ridge Cottage",
    description: "A secluded stone cottage surrounded by thick pine forests and misty mornings.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800" },
    price: 4200,
    location: "Kodaikanal",
    country: "India",
  },
  {
    title: "Nilgiri Mountain Home",
    description: "A peaceful hilltop bungalow surrounded by eucalyptus trees and tea estates.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501183638710-841dd1904471?q=80&w=800" },
    price: 5800,
    location: "Ooty",
    country: "India",
  },
  {
    title: "Konkan Coast Beach Shack",
    description: "Relaxed beachfront stay with wooden floors and incredible local seafood.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800" },
    price: 2800,
    location: "Tarkarli",
    country: "India",
  },
  {
    title: "Parvati Valley Glamping",
    description: "High-altitude luxury camping near the river with five-star amenities.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?q=80&w=800" },
    price: 9200,
    location: "Kasol",
    country: "India",
  },
  {
    title: "Bandra Art Deco Apartment",
    description: "A stylish, vintage-themed apartment in Mumbai's most vibrant neighborhood.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=800" },
    price: 10500,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Bamboo Grove Eco-Hut",
    description: "Sustainable bamboo hut tucked away in the wettest place on earth.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=800" },
    price: 3000,
    location: "Cherrapunji",
    country: "India",
  },
  {
    title: "Lakeside Stone Villa",
    description: "Hand-crafted stone villa offering peace, privacy, and stunning lake views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800" },
    price: 6700,
    location: "Bhimtal",
    country: "India",
  },
  {
    title: "Heritage Darjeeling Bungalow",
    description: "Colonial-era charm with views of the Kanchenjunga range and tea gardens.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=800" },
    price: 8900,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Varkala Cliffside Loft",
    description: "Stay right on the cliff with a bird's-eye view of the Arabian Sea surf.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800" },
    price: 3800,
    location: "Varkala",
    country: "India",
  },
  {
    title: "Sahyadri Valley Edge Villa",
    description: "A contemporary villa built on the edge of the valley with panoramic views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800" },
    price: 11500,
    location: "Mahabaleshwar",
    country: "India",
  },
  {
    title: "Ancient Hampi Guesthouse",
    description: "Stay amongst the boulders and ruins of the Vijayanagara empire.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=800" },
    price: 2200,
    location: "Hampi",
    country: "India",
  },
  {
    title: "Palm Breeze Beach Villa",
    description: "A private tropical villa surrounded by coconut groves near the sea.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800" },
    price: 7800,
    location: "Gokarna",
    country: "India",
  },
  {
    title: "Organic Apple Orchard Suite",
    description: "Sleep in a warm wooden suite located within a working fruit orchard.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800" },
    price: 4600,
    location: "Thanedar",
    country: "India",
  },
  {
    title: "Brahmaputra River Lodge",
    description: "Traditional Assamese architecture combined with modern comfort by the river.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1593181629936-11c609b8db9b?q=80&w=800" },
    price: 5400,
    location: "Guwahati",
    country: "India",
  },
  {
    title: "Lonavala Cloud Nine Villa",
    description: "Located at the highest ridge, offering views of the mist-covered Sahyadris.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=800" },
    price: 12000,
    location: "Lonavala",
    country: "India",
  },
  {
    title: "Coastal Luxury Penthouse",
    description: "Sleek minimalist design with a sprawling balcony facing the ocean sunrise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=800" },
    price: 8200,
    location: "Vizag",
    country: "India",
  },
  {
    title: "Naga Tribal Guest Hut",
    description: "Stay in a traditional Naga-style hut with modern comforts in the hills.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=800" },
    price: 2900,
    location: "Kohima",
    country: "India",
  },
  {
    title: "Hyderabad Designer Loft",
    description: "A minimalist designer space in the city's most happening financial district.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800" },
    price: 13500,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Sun-Drenched Kovalam House",
    description: "Bright airy interiors just a 2-minute walk from the Lighthouse beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=800" },
    price: 9800,
    location: "Kovalam",
    country: "India",
  },
  {
    title: "Kanha Jungle Eco-Lodge",
    description: "A sustainable luxury lodge built from local mud and timber near the tiger reserve.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?q=80&w=800" },
    price: 6200,
    location: "Kanha",
    country: "India",
  },
  {
    title: "Spiti Stone Shelter",
    description: "Rugged exterior but incredibly warm and cozy inside, facing the cold desert peaks.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?q=80&w=800" },
    price: 4400,
    location: "Spiti Valley",
    country: "India",
  },
  {
    title: "Sunset View Hilltop Bungalow",
    description: "The highest bungalow in the Aravallis, perfect for evening tea and quietude.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800" },
    price: 5900,
    location: "Mount Abu",
    country: "India",
  },
];

module.exports = { data: sampleListings };
